# theme: jekyll-theme-slate
theme: minima
title: with each drop
description: A melding of poetry, dance and sound, with a helping of machine learning.

github_username:  witheachdrop # DO NOT include the @ character, or else the build will fail!

header_pages:
  - about.md
  - climate.md
  - duet.md
  - artists.md
  - create.md