# theme: jekyll-theme-slate
theme: minima
title: With Each Drop
description: A melding of poetry, dance and sound, with a helping of machine learning.
header_pages:
  - about.md
  - climate.md
  - artists.md
  - test/test.md